// State and District data for India
export const stateDistrictData = {
  "Andhra Pradesh": [
    "Alluri Sitharama Raju",
    "Anakapalli",
    "Ananthapuramu",
    "Annamayya",
    "Bapatla",
    "Chittoor",
    "Dr. B.R. Ambedkar Konaseema",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Kakinada",
    "Krishna",
    "Kurnool",
    "NTR",
    "Nandyal",
    "Nellore",
    "Palnadu",
    "Parvathipuram Manyam",
    "Prakasam",
    "Sri Sathya Sai",
    "Srikakulam",
    "Tirupati",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa",
  ],
  "Arunachal Pradesh": [
    "Anjaw",
    "Bichom",
    "Changlang",
    "East Kameng",
    "East Siang",
    "Itanagar Capital Complex",
    "Kamle",
    "Keyi Panyor",
    "Kra Daadi",
    "Kurung Kumey",
    "Lepa Rada",
    "Lohit",
    "Longding",
    "Lower Dibang Valley",
    "Lower Siang",
    "Lower Subansiri",
    "Namsai",
    "Pakke-Kessang",
    "Papum Pare",
    "Shi Yomi",
    "Siang",
    "Tawang",
    "Tirap",
    "Upper Dibang Valley",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang",
  ],
  Assam: [
    "Bajali",
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tamulpur",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran",
  ],
  Chhattisgarh: [
    "Balod",
    "Baloda Bazar",
    "Balrampur Ramanujganj",
    "Bastar",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada",
    "Dhamtari",
    "Durg",
    "Gariaband",
    "Gaurela-Pendra-Marwahi",
    "Janjgir-Champa",
    "Jashpur",
    "Kabirdham",
    "Kanker",
    "Khairagarh-Chhuikhadan-Gandai",
    "Kondagaon",
    "Korba",
    "Korea",
    "Mahasamund",
    "Manendragarh-Chirmiri-Bharatpur",
    "Mohla-Manpur Ambagarh Chowki",
    "Mungeli",
    "Narayanpur",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sakti",
    "Sarangarh-Bilaigarh",
    "Sukma",
    "Surajpur",
    "Surguja",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang",
    "Devbhumi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kheda",
    "Kutch",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada",
    "Navsari",
    "Panchmahal",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Tapi",
    "Vadodara",
    "Valsad",
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribag",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Seraikela-Kharsawan",
    "Simdega",
    "West Singhbhum",
  ],
  Karnataka: [
    "Bagalkot",
    "Ballari",
    "Bangalore Rural",
    "Bangalore Urban",
    "Belagavi",
    "Bidar",
    "Bijapur",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikmagalur",
    "Chitradurga",
    "Dakshina Kannada",
    "Davanagere",
    "Dharwad",
    "Gadaga",
    "Hassan",
    "Haveri",
    "Kalaburagi",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysore",
    "Raichur",
    "Ramanagara",
    "Shimoga",
    "Tumakuru",
    "Udupi",
    "Uttara Kannada",
    "Vijayanagara",
    "Yadgir",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  "Madhya Pradesh": [
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Maihar",
    "Mandla",
    "Mandsaur",
    "Mauganj",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Niwari",
    "Pandhurna",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal",
  ],
  Manipur: [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kakching",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul",
  ],
  Meghalaya: [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "Eastern West Khasi Hills",
    "North Garo Hills",
    "Ri Bhoi",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Hnahthial",
    "Khawzawl",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Saitual",
    "Serchhip",
  ],
  Nagaland: [
    "Chümoukedima",
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Niuland",
    "Noklak",
    "Peren",
    "Phek",
    "Shamator",
    "Tseminyü",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Bhadrak",
    "Boudh",
    "Cuttack",
    "Debagarh",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar",
    "Khordha",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Subarnapur",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sahibzada Ajit Singh Nagar",
    "Sangrur",
    "Shahid Bhagat Singh Nagar",
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Anupgarh",
    "Balotra",
    "Banswara",
    "Baran",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Deeg",
    "Dholpur",
    "Didwana Kuchaman",
    "Dudu",
    "Dungarpur",
    "Gangapur city",
    "Hanumangarh",
    "Jaipur",
    "Jaipur Gramin",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Jodhpur Gramin",
    "Karauli",
    "Kekri",
    "Khairthal-Tijara",
    "Kota",
    "Kotputli-Behror",
    "Nagaur",
    "Neem Ka Thana",
    "Pali",
    "Phalodi",
    "Pratapgarh",
    "Rajsamand",
    "Salumbar",
    "Sanchore",
    "Sawai Madhopur",
    "Shahpura",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],
  Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi", "Pakyong", "Soreng"],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupattur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  Telangana: [
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hanamkonda",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhupalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Kumuram Bheem Asifabad",
    "Mahabubabad",
    "Mahbubnagar",
    "Mancherial",
    "Medak",
    "Medchal–Malkajgiri",
    "Mulugu",
    "Nagarkurnool",
    "Nalgonda",
    "Narayanpet",
    "Nirmal",
    "Nizamabad",
    "Peddapalli",
    "Rajanna Sircilla",
    "Ranga Reddy",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal",
    "Yadadri Bhuvanagiri",
  ],
  Tripura: ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Bagpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam BuddhaNagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushinagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Maldah",
    "Murshidabad",
    "Nadia",
    "North Parganas",
    "Paschim Bardhaman",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "South Parganas",
    "Uttar Dinajpur",
  ],
  "Jammu and Kashmir": ["Srinagar"],
} as const

export type StateName = keyof typeof stateDistrictData
export type DistrictName = (typeof stateDistrictData)[StateName][number]

export const states = Object.keys(stateDistrictData) as StateName[]

export const getDistrictsForState = (state: StateName): string[] => {
  return stateDistrictData[state] || []
}

// Sample area data - in real implementation this would come from API
export const sampleAreas: Record<string, string[]> = {
  "Mumbai City": ["Andheri", "Bandra", "Borivali", "Colaba", "Dadar", "Fort", "Juhu", "Lower Parel", "Malad", "Powai"],
  "Mumbai Suburban": [
    "Andheri East",
    "Andheri West",
    "Bandra East",
    "Bandra West",
    "Borivali East",
    "Borivali West",
    "Goregaon",
    "Kandivali",
    "Malad East",
    "Malad West",
    "Santacruz",
    "Vile Parle",
  ],
  Pune: [
    "Baner",
    "Hinjewadi",
    "Kothrud",
    "Viman Nagar",
    "Wakad",
    "Aundh",
    "Koregaon Park",
    "Camp",
    "Deccan",
    "Shivaji Nagar",
  ],
  Nashik: ["Nashik Road", "College Road", "Gangapur Road", "Panchavati", "Cidco", "Satpur"],
  Nagpur: ["Sitabuldi", "Dharampeth", "Sadar", "Hingna", "Wardha Road", "Kamptee Road"],
  Thane: ["Naupada", "Kopri", "Vartak Nagar", "Hiranandani Estate", "Ghodbunder Road", "Majiwada"],
  Aurangabad: ["Cidco", "Town Center", "Garkheda", "Waluj", "Jalna Road", "Beed Bypass"],

  // Delhi
  Delhi: [
    "Connaught Place",
    "Karol Bagh",
    "Lajpat Nagar",
    "Nehru Place",
    "Rajouri Garden",
    "Saket",
    "Dwarka",
    "Rohini",
    "Janakpuri",
    "Pitampura",
  ],

  // Karnataka
  "Bangalore Urban": [
    "Koramangala",
    "Indiranagar",
    "Whitefield",
    "Electronic City",
    "Jayanagar",
    "Malleshwaram",
    "HSR Layout",
    "BTM Layout",
    "Marathahalli",
    "Sarjapur",
  ],
  Mysore: ["Saraswathipuram", "Kuvempunagar", "Vijayanagar", "Hebbal", "Bogadi", "Nazarbad"],
  Mangalore: ["Kadri", "Kankanady", "Bejai", "Falnir", "Pandeshwar", "Balmatta"],

  // Tamil Nadu
  Chennai: [
    "Anna Nagar",
    "T. Nagar",
    "Velachery",
    "Adyar",
    "Nungambakkam",
    "Mylapore",
    "Tambaram",
    "Porur",
    "OMR",
    "ECR",
  ],
  Coimbatore: ["RS Puram", "Peelamedu", "Saibaba Colony", "Gandhipuram", "Race Course", "Singanallur"],
  Madurai: ["Anna Nagar", "K.K. Nagar", "Sellur", "Goripalayam", "Tallakulam", "Thiruparankundram"],

  // Telangana
  Hyderabad: [
    "Banjara Hills",
    "Jubilee Hills",
    "Gachibowli",
    "Hitech City",
    "Kondapur",
    "Madhapur",
    "Secunderabad",
    "Begumpet",
    "Ameerpet",
    "Kukatpally",
  ],

  // West Bengal
  Kolkata: [
    "Salt Lake",
    "Park Street",
    "Ballygunge",
    "Alipore",
    "New Town",
    "Rajarhat",
    "Howrah",
    "Dum Dum",
    "Behala",
    "Jadavpur",
  ],

  // Gujarat
  Ahmedabad: [
    "Satellite",
    "Vastrapur",
    "Bopal",
    "Prahlad Nagar",
    "Navrangpura",
    "C.G. Road",
    "Maninagar",
    "Naranpura",
    "Ambawadi",
    "Paldi",
  ],
  Surat: ["Adajan", "Vesu", "Althan", "Piplod", "Citylight", "Rander", "Udhna", "Katargam", "Varachha", "Nanpura"],
  Vadodara: ["Alkapuri", "Fatehgunj", "Sayajigunj", "Manjalpur", "Gotri", "Akota"],

  // Rajasthan
  Jaipur: [
    "Malviya Nagar",
    "Vaishali Nagar",
    "Mansarovar",
    "C-Scheme",
    "Bani Park",
    "Raja Park",
    "Tonk Road",
    "Ajmer Road",
    "Sikar Road",
    "Civil Lines",
  ],
  Jodhpur: ["Ratanada", "Shastri Nagar", "Chopasni Housing Board", "Paota", "Sardarpura", "Basni"],
  Udaipur: ["Fateh Sagar", "Sukhadia Circle", "Hiran Magri", "Pratap Nagar", "Sector 14", "New Fatehpura"],

  // Uttar Pradesh
  Lucknow: ["Hazratganj", "Gomti Nagar", "Indira Nagar", "Aliganj", "Mahanagar", "Jankipuram"],
  "Kanpur Nagar": ["Civil Lines", "Swaroop Nagar", "Kidwai Nagar", "Govind Nagar", "Kalyanpur", "Barra"],
  Agra: ["Sadar Bazaar", "Dayalbagh", "Kamla Nagar", "Sikandra", "Tajganj", "Lohamandi"],
  Varanasi: ["Cantonment", "Sigra", "Lanka", "Mahmoorganj", "Sarnath", "Bhelupur"],
  Ghaziabad: ["Raj Nagar", "Vasundhara", "Indirapuram", "Crossings Republik", "Kaushambi", "Vaishali"],

  // Haryana
  Gurugram: [
    "DLF Phase 1",
    "DLF Phase 2",
    "DLF Phase 3",
    "Sector 14",
    "Sector 29",
    "Golf Course Road",
    "Sohna Road",
    "MG Road",
    "Cyber City",
    "New Gurgaon",
  ],
  Faridabad: ["Sector 15", "Sector 16", "Sector 21", "NIT", "Old Faridabad", "Greater Faridabad"],

  // Punjab
  Ludhiana: ["Model Town", "Civil Lines", "Pakhowal Road", "Ferozepur Road", "BRS Nagar", "Sarabha Nagar"],
  Amritsar: ["Lawrence Road", "Ranjit Avenue", "Majitha Road", "GT Road", "Chheharta", "Putlighar"],

  // Madhya Pradesh
  Indore: ["Vijay Nagar", "Palasia", "Bhawarkuan", "Rau", "Dewas Naka", "Sapna Sangeeta"],
  Bhopal: ["New Market", "MP Nagar", "Arera Colony", "Shahpura", "Kolar", "Berasia Road"],

  // Kerala
  Thiruvananthapuram: ["Pattom", "Kesavadasapuram", "Vazhuthacaud", "Ulloor", "Vellayambalam", "Statue"],
  Ernakulam: ["Marine Drive", "Panampilly Nagar", "Kadavanthra", "Kaloor", "Palarivattom", "Edappally"],
  Kozhikode: ["Mavoor Road", "Kannur Road", "Palayam", "Westhill", "Chevayur", "Ramanattukara"],

  // Bihar
  Patna: ["Boring Road", "Fraser Road", "Kankarbagh", "Rajendra Nagar", "Danapur", "Patliputra"],

  // Odisha
  Bhubaneswar: ["Saheed Nagar", "Jaydev Vihar", "Khandagiri", "Patia", "Chandrasekharpur", "Unit 8"],

  // Assam
  "Kamrup Metropolitan": ["Fancy Bazaar", "Paltan Bazaar", "Chandmari", "Hatigaon", "Beltola", "Garchuk"],

  // Jharkhand
  Ranchi: ["Main Road", "Harmu", "Doranda", "Kanke", "Ratu Road", "Circular Road"],

  // Chhattisgarh
  Raipur: ["Shankar Nagar", "Pandri", "Tatibandh", "Devendra Nagar", "Civil Lines", "Moudhapara"],

  // Uttarakhand
  Dehradun: ["Rajpur Road", "Gandhi Road", "Clement Town", "Patel Nagar", "Sahastradhara Road", "ISBT"],

  // Himachal Pradesh
  Shimla: ["Mall Road", "Ridge", "Lakkar Bazaar", "Sanjauli", "New Shimla", "Chhota Shimla"],

  // Jammu and Kashmir
  Srinagar: ["Lal Chowk", "Rajbagh", "Jawahar Nagar", "Gogji Bagh", "Bemina", "Hyderpora"],

  // Goa
  "North Goa": ["Panaji", "Mapusa", "Calangute", "Baga", "Anjuna", "Arambol"],
  "South Goa": ["Margao", "Vasco da Gama", "Ponda", "Colva", "Benaulim", "Palolem"],
}
